


var lookForPronouns = (function () {

    var pronouns = [{
            "name": "i'",
            "class": "",
            "plurality": "singular",
            "person": "first",
            "describe": "subject"
        }, {
            "name": "ɪ'",
            "class": "",
            "plurality": "singular",
            "person": "second",
            "describe": "subject"
        }, {
            "name": "ɔ'",
            "class": "",
            "plurality": "singular",
            "person": "third",
            "describe": "subject"
        }, {
            "name": "rʌ'",
            "class": "",
            "plurality": "singular",
            "person": "third",
            "describe": "subject"
        }, {
            "name": "kʌ'",
            "class": "",
            "plurality": "singular",
            "person": "third",
            "describe": "subject"
        }, {
            "name": "dʌ'",
            "class": "",
            "plurality": "singular",
            "person": "third",
            "describe": "subject"
        }, {
            "name": "əŋ'",
            "class": "",
            "plurality": "singular",
            "person": "third",
            "describe": "subject"
        }, {
            "name": "pʌ'",
            "class": "",
            "plurality": "singular",
            "person": "third",
            "describe": "subject"
        }, {
            "name": "sʌ'",
            "class": "",
            "plurality": "plural",
            "person": "first",
            "describe": "subject"
        }, {
            "name": "nu'",
            "class": "",
            "plurality": "plural",
            "person": "second",
            "describe": "subject"
        }, {
            "name": "aŋ'",
            "class": "",
            "plurality": "plural",
            "person": "third",
            "describe": "subject"
        }, {
            "name": "a'",
            "class": "",
            "plurality": "plural",
            "person": "third",
            "describe": "subject"
        },{
            "name": "ɛ'",
            "class": "",
            "plurality": "plural",
            "person": "third",
            "describe": "subject"
        }, {
            "name": "tʌ'",
            "class": "",
            "plurality": "plural",
            "person": "third",
            "describe": "subject"
        }, {
            "name": "nʌ'",
            "class": "",
            "plurality": "plural",
            "person": "third",
            "describe": "subject"
        }, {
            "name": "cʌ'",
            "class": "",
            "plurality": "plural",
            "person": "third",
            "describe": "subject"
        }, {
            "name": "mʌ'",
            "class": "",
            "plurality": "plural",
            "person": "third",
            "describe": "subject"
        }, {
            "name": "ma'",
            "class": "",
            "plurality": "plural",
            "person": "fourth",
            "describe": "progressive/subjective"
        }, {
            "name": "mi",
            "class": "",
            "plurality": "singular",
            "person": "first",
            "describe": "object"
        }, {
            "name": "mu",
            "class": "",
            "plurality": "singular",
            "person": "second",
            "describe": "object"
        }, {
            "name": "su",
            "class": "",
            "plurality": "plural",
            "person": "first",
            "describe": "object"
        }, {
            "name": "nu",
            "class": "",
            "plurality": "plural",
            "person": "second",
            "describe": "object"
        }, {
            "name": "ŋa",
            "class": "",
            "plurality": "plural",
            "person": "first",
            "describe": "object"
        }, {
            "name": "nuŋ",
            "class": "",
            "plurality": "plural",
            "person": "second",
            "describe": "object"
        }, {
            "name": "ta'",
            "class": "",
            "plurality": "plural",
            "person": "third",
            "describe": "permisiative/subjective"
        }, {
            "name": "minɛ'",
            "class": "",
            "plurality": "singular",
            "person": "first",
            "describe": "subjectAccusational"
        }, {
            "name": "munɔ'",
            "class": "",
            "plurality": "singular",
            "person": "second",
            "describe": "subjectAccusational"
        }, {
            "name": "kɔ̄ŋ'",
            "class": "",
            "plurality": "singular",
            "person": "third",
            "describe": "subjectAccusational"
        }, {
            "name": "kɔ̄n'",
            "class": "",
            "plurality": "singular",
            "person": "third",
            "describe": "subjectAccusational"
        }, {
            "name": "sa'",
            "class": "",
            "plurality": "plural",
            "person": "first",
            "describe": "subjectAccusational"
        }, {
            "name": "sā'",
            "class": "",
            "plurality": "plural",
            "person": "first",
            "describe": "subjectAccusational"
        }, {
            "name": "na'",
            "class": "",
            "plurality": "plural",
            "person": "third",
            "describe": "subjectAccusational"
        }, {
            "name": "minɛ̄ŋ",
            "class": "",
            "plurality": "singular",
            "person": "first",
            "describe": "objectAccusational"
        }, {
            "name": "munɔ̄ŋ",
            "class": "",
            "plurality": "singular",
            "person": "second",
            "describe": "objectAccusational"
        }, {
            "name": "sāŋ",
            "class": "",
            "plurality": "plural",
            "person": "first",
            "describe": "objectAccusational"
        }, {
            "name": "nāŋ",
            "class": "",
            "plurality": "plural",
            "person": "second",
            "describe": "objectAccusational"
        }, {
            "name": "na",
            "class": "",
            "plurality": "plural",
            "person": "third",
            "describe": "objectAccusational"
        }, {
            "name": "mɛ'",
            "class": "",
            "plurality": "singular",
            "person": "first",
            "describe": "subjectProgressive/subjectPerfectum"
        }, {
            "name": "mɔŋ'",
            "class": "",
            "plurality": "singular",
            "person": "second",
            "describe": "subjectProgressiveQuestionative/subjectPerfectum"
        }, {
            "name": "mɔ'",
            "class": "",
            "plurality": "singular",
            "person": "third",
            "describe": "subjectProgressive/subjectPerfectum"
        }, {
            "name": "maŋ'",
            "class": "",
            "plurality": "plural",
            "person": "third",
            "describe": "subjectProgressive/subjectPerfectum"
        }, {
            "name": "p'",
            "class": "",
            "plurality": "infinitive",
            "person": "fourth",
            "describe": "infinitive/subjective"
        }, {
            "name": "minɛ",
            "class": "",
            "plurality": "singular",
            "person": "first",
            "describe": "directAssertative/objective"
        }, {
            "name": "minɛŋ",
            "class": "",
            "plurality": "singular",
            "person": "first",
            "describe": "directAssertative/objective"
        }, {
            "name": "munɔ",
            "class": "",
            "plurality": "singular",
            "person": "second",
            "describe": "directAssertative/objective"
        }, {
            "name": "munɔŋ",
            "class": "",
            "plurality": "singular",
            "person": "second",
            "describe": "directAssertative/objective"
        }, {
            "name": "kɔnɔ",
            "class": "",
            "plurality": "singular",
            "person": "third",
            "describe": "directAssertative/objective"
        }, {
            "name": "kɔnɔŋ",
            "class": "",
            "plurality": "singular",
            "person": "third",
            "describe": "directAssertative/objective"
        }, {
            "name": "ŋə",
            "class": "",
            "plurality": "singular",
            "person": "third",
            "describe": "directAssertative/objective"
        }, {
            "name": "mə",
            "class": "",
            "plurality": "singular",
            "person": "third",
            "describe": "directAssertative/objective"
        }, {
            "name": "rə",
            "class": "",
            "plurality": "singular",
            "person": "third",
            "describe": "directAssertative/objective"
        }, {
            "name": "tə",
            "class": "",
            "plurality": "singular",
            "person": "third",
            "describe": "directAssertative/objective"
        }, {
            "name": "kə",
            "class": "",
            "plurality": "singular",
            "person": "third",
            "describe": "directAssertative/objective"
        }, {
            "name": "də",
            "class": "",
            "plurality": "singular",
            "person": "third",
            "describe": "directAssertative/objective"
        }, {
            "name": "pə",
            "class": "",
            "plurality": "singular",
            "person": "third",
            "describe": "directAssertative/objective"
        }, {
            "name": "yə",
            "class": "",
            "plurality": "singular",
            "person": "third",
            "describe": "directAssertative/objective"
        }, {
            "name": "nə",
            "class": "",
            "plurality": "singular",
            "person": "third",
            "describe": "directAssertative/objective"
        }, {
            "name": "sā'",
            "class": "",
            "plurality": "plural",
            "person": "first",
            "describe": "descriptiveObjectAccusational"
        }, {
            "name": "nā'",
            "class": "",
            "plurality": "plural",
            "person": "third",
            "describe": "descriptiveObjectAccusational"
        }, {
            "name": "kɔ",
            "class": "ɔ́'/ù'/'əŋ",
            "plurality": "singular",
            "person": "third",
            "describe": "infinitive/hypotheticalObjective/objective"
        }, {
            "name": "ŋi",
            "class": "ə́ŋ'/ə̀'",
            "plurality": "singular",
            "person": "third",
            "describe": "infinitive/hypotheticalObjective/objective"
        }, {
            "name": "yi",
            "class": "ɛ́'/ɛ̀'/áŋ'/a",
            "plurality": "Plural",
            "person": "third",
            "describe": "infinitive/hypotheticalObjective/objective"
        }, {
            "name": "ri",
            "class": "rə́'/r̀ʌ'/ró'",
            "plurality": "singular",
            "person": "third",
            "describe": "infinitive/hypotheticalObjective/objective"
        }, {
            "name": "ni",
            "class": "nə́'/ǹʌ'",
            "plurality": "Plural",
            "person": "third",
            "describe": "infinitive/hypotheticalObjective/objective"
        }, {
            "name": "ki",
            "class": "kə́'/k̀ʌ'/ḱ'",
            "plurality": "singular",
            "person": "third",
            "describe": "infinitive/hypotheticalObjective/objective"
        }, {
            "name": "ti",
            "class": "tə́'/t̀ʌ'/t́'/t'",
            "plurality": "Plural",
            "person": "third",
            "describe": "infinitive/hypotheticalObjective/objective"
        }, {
            "name": "pi",
            "class": "pə́'/p̀ʌ'",
            "plurality": "singular",
            "person": "third",
            "describe": "infinitive/hypotheticalObjective/objective"
        }, {
            "name": "ci",
            "class": "",
            "plurality": "singular",
            "person": "third",
            "describe": "infinitive/hypotheticalObjective/objective"
        }, {
            "name": "ŋi",
            "class": "cə́'/c̀ʌ'/ə́ŋ'/ə̀'",
            "plurality": "Plural",
            "person": "third",
            "describe": "infinitive/hypotheticalObjective/objective"
        }, {
            "name": "di",
            "class": "də́'/d̀ʌ'",
            "plurality": "singular",
            "person": "third",
            "describe": "infinitive/hypotheticalObjective/objective"
        }, {
            "name": "dɛ",
            "class": "də́'/d̀ʌ'/ALL",
            "plurality": "singular",
            "person": "third",
            "describe": "infinitive/hypotheticalObjective/objective"
        },{
            "name": "ɱmi",
            "class": "mə́'/m̀ʌ'",
            "plurality": "Plural",
            "person": "third",
            "describe": "infinitive/hypotheticalObjective/objective"
        }, {
            "name": "ma",
            "class": "mə́'/m̀ʌ'",
            "plurality": "Plural",
            "person": "third",
            "describe": "hypotheticalObjective"
        }, {
            "name": "ɔwe'",
            "class": "ù'/ɔ́'",
            "plurality": "singular",
            "person": "third",
            "describe": "discriptional/subject"
        }, {
            "name": "aŋe'",
            "class": "ɔ́'/áŋ'/à'/cə́'/c̀ʌ'/ə́ŋ'/ə̀'",
            "plurality": "Plural",
            "person": "third",
            "describe": "discriptional/subject"
        }, {
            "name": "əŋe'",
            "class": "ə́ŋ'/ə̀'",
            "plurality": "singular",
            "person": "third",
            "describe": "discriptiona/subject"
        }, {
            "name": "ɛye'",
            "class": "ɛ́'/ɛ̀'",
            "plurality": "Plural",
            "person": "third",
            "describe": "discriptiona/subject"
        }, {
            "name": "əre'",
            "class": "rə́'/r̀ʌ'/ró'",
            "plurality": "singular",
            "person": "third",
            "describe": "discriptiona/subject"
        }, {
            "name": "əne'",
            "class": "nə́'/ǹʌ'",
            "plurality": "Plural",
            "person": "third",
            "describe": "discriptiona/subject"
        }, {
            "name": "əke'",
            "class": "kə́'/k̀ʌ'/ḱ'",
            "plurality": "singular",
            "person": "third",
            "describe": "discriptiona/subject"
        }, {
            "name": "əte'",
            "class": "tə́'/t̀ʌ'/t́'/t'",
            "plurality": "Plural",
            "person": "third",
            "describe": "discriptiona/subject"
        }, {
            "name": "əpe'",
            "class": "pə́'/p̀ʌ'",
            "plurality": "singular",
            "person": "third",
            "describe": "discriptiona/subject"
        }, {
            "name": "aŋe'",
            "class": "cə́'/c̀ʌ'/ə́ŋ'/ə̀'",
            "plurality": "Plural",
            "person": "third",
            "describe": "discriptiona/subject"
        }, {
            "name": "əde'",
            "class": "də́'/d̀ʌ'",
            "plurality": "singular",
            "person": "third",
            "describe": "discriptiona/subject"
        }, {
            "name": "əme'",
            "class": "mə́'/m̀ʌ'",
            "plurality": "singular",
            "person": "third",
            "describe": "infinitive/hypotheticalObjective/stubjective"
        }, {
            "name": "ɱme'",
            "class": "mə́'/m̀ʌ'",
            "plurality": "singular",
            "person": "third",
            "describe": "infinitive/hypotheticalObjective/stubjective"
        }, {
            "name": "ma",
            "class": "mə́'/m̀ʌ'",
            "plurality": "Plural",
            "person": "third",
            "describe": "hypotheticalObjective"
        }, {
            "name": "ɔwe",
            "class": "ù/ɔ́",
            "plurality": "singular",
            "person": "third",
            "describe": "discriptiona/subject"
        }, {
            "name": "aŋe",
            "class": "ɔ́'/áŋ'/à'/cə́'/c̀ʌ'/ə́ŋ'/ə̀'",
            "plurality": "Plural",
            "person": "third",
            "describe": "discriptiona/subject"
        }, {
            "name": "əŋe",
            "class": "ə́ŋ'/ə̀'",
            "plurality": "singular",
            "person": "third",
            "describe": "discriptiona/subject"
        }, {
            "name": "ɛye",
            "class": "ɛ́'/ɛ̀'",
            "plurality": "Plural",
            "person": "third",
            "describe": "discriptiona/subject"
        }, {
            "name": "əre",
            "class": "rə́'/r̀ʌ'/ró'",
            "plurality": "singular",
            "person": "third",
            "describe": "discriptiona/subject"
        }, {
            "name": "əne",
            "class": "nə́'/ǹʌ'",
            "plurality": "Plural",
            "person": "third",
            "describe": "discriptiona/subject"
        }, {
            "name": "əke",
            "class": "kə́'/k̀ʌ'/ḱ'",
            "plurality": "singular",
            "person": "third",
            "describe": "discriptiona/subject"
        }, {
            "name": "əte",
            "class": "tə́'/t̀ʌ'/t́'/t'",
            "plurality": "Plural",
            "person": "third",
            "describe": "discriptiona/subject"
        }, {
            "name": "əpe",
            "class": "pə́'/p̀ʌ'",
            "plurality": "singular",
            "person": "third",
            "describe": "discriptiona/subject"
        }, {
            "name": "aŋe",
            "class": "cə́'/c̀ʌ'/ə́ŋ'/ə̀'",
            "plurality": "Plural",
            "person": "third",
            "describe": "discriptiona/subject"
        }, {
            "name": "əde",
            "class": "də́'/d̀ʌ'",
            "plurality": "singular",
            "person": "third",
            "describe": "discriptiona/subject"
        }, {
            "name": "əme",
            "class": "mə́'/m̀ʌ'",
            "plurality": "singular",
            "person": "third",
            "describe": "infinitive/hypotheticalObjective/stubjective"
        }, {
            "name": "ɱme",
            "class": "mə́'/m̀ʌ'",
            "plurality": "singular",
            "person": "third",
            "describe": "infinitive/hypotheticalObjective/stubjective"
        }, {
            "name": "ɔwɔŋ",
            "class": "ù'/ɔ́'",
            "plurality": "Plural",
            "person": "third",
            "describe": "locational/closeRelativePositional"
        }, {
            "name": "aŋəŋ",
            "class": "ɔ́'/áŋ'/à'/cə́'/c̀ʌ'/ə́ŋ'/ə̀'",
            "plurality": "Plural",
            "person": "third",
            "describe": "locational/closeRelativePositional"
        }, {
            "name": "əŋəŋ",
            "class": "ə́ŋ'/ə̀'",
            "plurality": "Plural",
            "person": "third",
            "describe": "locational/closeRelativePositional"
        }, {
            "name": "ɛyɛŋ",
            "class": "ɛ́'/ɛ̀'",
            "plurality": "Plural",
            "person": "third",
            "describe": "locational/closeRelativePositional"
        }, {
            "name": "ərəŋ",
            "class": "rə́'/r̀ʌ'/ró'",
            "plurality": "Plural",
            "person": "third",
            "describe": "locational/closeRelativePositional"
        }, {
            "name": "ənəŋ",
            "class": "nə́'/ǹʌ'",
            "plurality": "Plural",
            "person": "third",
            "describe": "locational/closeRelativePositional"
        }, {
            "name": "əkəŋ",
            "class": "kə́'/k̀ʌ'/ḱ'",
            "plurality": "Plural",
            "person": "third",
            "describe": "locational/closeRelativePositional"
        }, {
            "name": "ətəŋ",
            "class": "tə́'/t̀ʌ'/t́'/t'",
            "plurality": "Plural",
            "person": "third",
            "describe": "locational/closeRelativePositional"
        }, {
            "name": "əpəŋ",
            "class": "pə́'/p̀ʌ'",
            "plurality": "Plural",
            "person": "third",
            "describe": "locational/closeRelativePositional"
        }, {
            "name": "aŋəŋ",
            "class": "cə́'/c̀ʌ'/ə́ŋ'/ə̀'",
            "plurality": "Plural",
            "person": "third",
            "describe": "locational/closeRelativePositional"
        }, {
            "name": "əŋəŋ",
            "class": "cə́'/c̀ʌ'/ə́ŋ'/ə̀'",
            "plurality": "Plural",
            "person": "third",
            "describe": "locational/closeRelativePositional"
        }, {
            "name": "əməŋ",
            "class": "mə́'/m̀ʌ'",
            "plurality": "Plural",
            "person": "third",
            "describe": "locational/closeRelativePositional"
        }, {
            "name": "yɔŋ",
            "class": "ɛ́'/ɛ̀'",
            "plurality": "Singular",
            "person": "third",
            "describe": "objectivalPronounPosessives/objectivalPronounSingular/objectivalPronounThirdPerson"
        }, {
            "name": "rɔŋ",
            "class": "rə́'/r̀ʌ'/ró'",
            "plurality": "Singular",
            "person": "third",
            "describe": "objectivalPronounPosessives/objectivalPronounSingular/objectivalPronounThirdPerson"
        }, {
            "name": "nɔŋ",
            "class": "nə́'/ǹʌ'",
            "plurality": "Singular",
            "person": "third",
            "describe": "objectivalPronounPosessives/objectivalPronounSingular/objectivalPronounThirdPerson"
        }, {
            "name": "kɔŋ",
            "class": "kə́'/k̀ʌ'/ḱ'/ɔ́'/ù'/ɔ́'/áŋ'/à'/cə́'/c̀ʌ'/ə́ŋ'/ə̀'",
            "plurality": "Singular",
            "person": "third",
            "describe": "objectivalPronounPosessives/objectivalPronounSingular/objectivalPronounThirdPerson"
        }, {
            "name": "tɔŋ",
            "class": "tə́'/t̀ʌ'/t́'/t'",
            "plurality": "Singular",
            "person": "third",
            "describe": "objectivalPronounPosessives/objectivalPronounSingular/objectivalPronounThirdPerson"
        }, {
            "name": "pɔŋ",
            "class": "pə́'/p̀ʌ'",
            "plurality": "Singular",
            "person": "third",
            "describe": "objectivalPronounPosessives/objectivalPronounSingular/objectivalPronounThirdPerson"
        }, {
            "name": "kɔŋ",
            "class": "cə́'/c̀ʌ'/ə́ŋ'/ə̀'",
            "plurality": "Singular",
            "person": "third",
            "describe": "objectivalPronounPosessives/objectivalPronounSingular/objectivalPronounThirdPerson"
        }, {
            "name": "dɔŋ",
            "class": "də́'/d̀ʌ'",
            "plurality": "Singular",
            "person": "third",
            "describe": "objectivalPronounPosessives/objectivalPronounSingular/objectivalPronounThirdPerson"
        }, {
            "name": "ŋɔŋ",
            "class": "ə́ŋ'/ə̀",
            "plurality": "Singular",
            "person": "third",
            "describe": "objectivalPronounPosessives/objectivalPronounSingular/objectivalPronounThirdPerson"
        },  {
            "name": "ŋaŋ",
            "class": "ə́ŋ'/ə̀",
            "plurality": "Singular",
            "person": "third",
            "describe": "objectivalPronounPosessives/objectivalPronounSingular/objectivalPronounThirdPerson"
        },{
            "name": "mɔŋ",
            "class": "mə́'/m̀ʌ'",
            "plurality": "Singular",
            "person": "third",
            "describe": "objectivalPronounPosessives/objectivalPronounSingular/objectivalPronounThirdPerson"
        }, {
            "name": "waci",
            "class": "ù'/ɔ́'",
            "plurality": "Plural",
            "person": "third",
            "describe": "relapsatives"
        }, {
            "name": "ŋaci",
            "class": "ɔ́'/áŋ'/à'/cə́'/c̀ʌ'/ə́ŋ'/ə̀'/ə́ŋ'/ə̀'",
            "plurality": "Plural",
            "person": "third",
            "describe": "relapsatives"
        }, {
            "name": "yaci",
            "class": "ɛ́'/ɛ̀'",
            "plurality": "Plural",
            "person": "third",
            "describe": "relapsatives"
        }, {
            "name": "raci",
            "class": "rə́'/r̀ʌ'/ró'",
            "plurality": "Plural",
            "person": "third",
            "describe": "relapsatives"
        }, {
            "name": "naci",
            "class": "nə́'/ǹʌ'",
            "plurality": "Plural",
            "person": "third",
            "describe": "relapsatives"
        }, {
            "name": "kaci",
            "class": "kə́'/k̀ʌ'/ḱ'",
            "plurality": "Plural",
            "person": "third",
            "describe": "relapsatives"
        }, {
            "name": "taci",
            "class": "tə́'/t̀ʌ'/t́'/t'",
            "plurality": "Plural",
            "person": "third",
            "describe": "relapsatives"
        }, {
            "name": "paci",
            "class": "pə́'/p̀ʌ'",
            "plurality": "Plural",
            "person": "third",
            "describe": "relapsatives"
        }, {
            "name": "pəci",
            "class": "pə́'/p̀ʌ'",
            "plurality": "Plural",
            "person": "third",
            "describe": "relapsatives"
        }, {
            "name": "ŋaci",
            "class": "cə́'/c̀ʌ'/ə́ŋ'/ə̀'",
            "plurality": "Plural",
            "person": "third",
            "describe": "relapsatives"
        }, {
            "name": "daci",
            "class": "də́'/d̀ʌ'/dó'",
            "plurality": "Plural",
            "person": "third",
            "describe": "relapsatives"
        }, {
            "name": "maci",
            "class": "mə́'/m̀ʌ'",
            "plurality": "Plural",
            "person": "third",
            "describe": "relapsatives"
        }, {
            "name": "ŋa'",
            "class": "ɔ́'/áŋ'/à'/cə́'/c̀ʌ'/ə́ŋ'/ə̀'",
            "plurality": "singular",
            "person": "third",
            "describe": "simoultaniousalState/subjectAccusational"
        }, {
            "name": "kɔnɔ'",
            "class": "ɔ́'/ù'/'əŋ",
            "plurality": "singular",
            "person": "third",
            "describe": "simoultaniousalState/subjectAccusational"
        }, {
            "name": "kɔ̄n'",
            "class": "ɔ́'/ù'/'əŋ",
            "plurality": "singular",
            "person": "third",
            "describe": "simoultaniousalState/subjectAccusational"
        }, {
            "name": "kɔ̄ŋ'",
            "class": "ɔ́'/ù'/'əŋ",
            "plurality": "singular",
            "person": "third",
            "describe": "simoultaniousalState/subjectAccusational"
        }, {
            "name": "ŋi'",
            "class": "ə́ŋ'/ə̀'",
            "plurality": "singular",
            "person": "third",
            "describe": "subjectAccusational"
        }, {
            "name": "yi'",
            "class": "ɛ́'/ɛ̀'",
            "plurality": "Plural",
            "person": "third",
            "describe": "subjectAccusational"
        }, {
            "name": "ri'",
            "class": "rə́'/r̀ʌ'/ró'",
            "plurality": "singular",
            "person": "third",
            "describe": "subjectAccusational"
        }, {
            "name": "ni'",
            "class": "nə́'/ǹʌ'",
            "plurality": "Plural",
            "person": "third",
            "describe": "subjectAccusational"
        }, {
            "name": "ki'",
            "class": "kə́'/k̀ʌ'/ḱ'",
            "plurality": "singular",
            "person": "third",
            "describe": "subjectAccusational"
        }, {
            "name": "ti'",
            "class": "tə́'/t̀ʌ'/t́'/t'",
            "plurality": "Plural",
            "person": "third",
            "describe": "subjectAccusational"
        }, {
            "name": "pi'",
            "class": "pə́'/p̀ʌ'",
            "plurality": "singular",
            "person": "third",
            "describe": "subjectAccusational"
        }, {
            "name": "ŋi'",
            "class": "cə́'/c̀ʌ'/ə́ŋ'/ə̀'",
            "plurality": "Plural",
            "person": "third",
            "describe": "subjectAccusational"
        }, {
            "name": "di'",
            "class": "də́'/d̀ʌ'",
            "plurality": "singular",
            "person": "third",
            "describe": "subjectAccusational"
        }, {
            "name": "mi'",
            "class": "mə́'/m̀ʌ'",
            "plurality": "Plural",
            "person": "third",
            "describe": "subjectAccusational"
        }, {
            "name": "ŋə'",
            "class": "ə́ŋ'/ə̀'",
            "plurality": "singular",
            "person": "third",
            "describe": "simoultaniousalState/subjectAccusational"
        }, {
            "name": "yə'",
            "class": "ɛ́'/ɛ̀'",
            "plurality": "Plural",
            "person": "third",
            "describe": "simoultaniousalState/subjectAccusational"
        }, {
            "name": "rə'",
            "class": "rə́'/r̀ʌ'/ró'",
            "plurality": "singular",
            "person": "third",
            "describe": "simoultaniousalState/subjectAccusational"
        }, {
            "name": "nə'",
            "class": "nə́'/ǹʌ'",
            "plurality": "Plural",
            "person": "third",
            "describe": "simoultaniousalState/subjectAccusational"
        }, {
            "name": "kə'",
            "class": "kə́'/k̀ʌ'/ḱ'",
            "plurality": "singular",
            "person": "third",
            "describe": "simoultaniousalState/subjectAccusational"
        }, {
            "name": "tə'",
            "class": "tə́'/t̀ʌ'/t́'/t'",
            "plurality": "Plural",
            "person": "third",
            "describe": "simoultaniousalState/subjectAccusational"
        }, {
            "name": "pə'",
            "class": "pə́'/p̀ʌ'",
            "plurality": "singular",
            "person": "third",
            "describe": "simoultaniousalState/subjectAccusational"
        }, {
            "name": "ŋə'",
            "class": "cə́'/c̀ʌ'/ə́ŋ'/ə̀'",
            "plurality": "Plural",
            "person": "third",
            "describe": "simoultaniousalState/subjectAccusational"
        }, {
            "name": "də'",
            "class": "də́'/d̀ʌ'",
            "plurality": "singular",
            "person": "third",
            "describe": "simoultaniousalState/subjectAccusational"
        }, {
            "name": "mə'",
            "class": "mə́'/m̀ʌ'",
            "plurality": "Plural",
            "person": "third",
            "describe": "simoultaniousalState/subjectAccusational"
        }, {
            "name": "ŋāŋ",
            "class": "ɔ́'/áŋ'/à'/cə́'/c̀ʌ'/ə́ŋ'/ə̀'",
            "plurality": "singular",
            "person": "third",
            "describe": "simoultaniousalState/objectAccusational"
        }, {
            "name": "kɔnɔ̄ŋ",
            "class": "ɔ́'/ù'/'əŋ",
            "plurality": "singular",
            "person": "third",
            "describe": "simoultaniousalState/objectAccusational"
        }, {
            "name": "ŋɛ̄ŋ",
            "class": "ə́ŋ'/ə̀'",
            "plurality": "singular",
            "person": "third",
            "describe": "simoultaniousalState/objectAccusational"
        }, {
            "name": "yɛ̄ŋ",
            "class": "ɛ́'/ɛ̀'",
            "plurality": "Plural",
            "person": "third",
            "describe": "simoultaniousalState/objectAccusational"
        }, {
            "name": "rɛ̄ŋ",
            "class": "rə́'/r̀ʌ'/ró'",
            "plurality": "singular",
            "person": "third",
            "describe": "simoultaniousalState/objectAccusational"
        }, {
            "name": "nɛ̄ŋ",
            "class": "nə́'/ǹʌ'",
            "plurality": "Plural",
            "person": "third",
            "describe": "simoultaniousalState/objectAccusational"
        }, {
            "name": "kɛ̄ŋ",
            "class": "kə́'/k̀ʌ'/ḱ'",
            "plurality": "singular",
            "person": "third",
            "describe": "simoultaniousalState/objectAccusational"
        }, {
            "name": "tɛ̄ŋ",
            "class": "tə́'/t̀ʌ'/t́'/t'",
            "plurality": "Plural",
            "person": "third",
            "describe": "simoultaniousalState/objectAccusational"
        }, {
            "name": "pɛ̄ŋ",
            "class": "pə́'/p̀ʌ'",
            "plurality": "singular",
            "person": "third",
            "describe": "simoultaniousalState/objectAccusational"
        }, {
            "name": "ŋɛ̄ŋ",
            "class": "cə́'/c̀ʌ'/ə́ŋ'/ə̀'",
            "plurality": "Plural",
            "person": "third",
            "describe": "simoultaniousalState/objectAccusational"
        }, {
            "name": "cɛ̄ŋ",
            "class": "",
            "plurality": "Plural",
            "person": "third",
            "describe": "simoultaniousalState/objectAccusational/infinitive"
        }, {
            "name": "dɛ̄ŋ",
            "class": "də́'/d̀ʌ'",
            "plurality": "singular",
            "person": "third",
            "describe": "simoultaniousalState/objectAccusational"
        }, {
            "name": "mɛ̄ŋ",
            "class": "mə́'/m̀ʌ'",
            "plurality": "Plural",
            "person": "third",
            "describe": "simoultaniousalState/objectAccusational"
        }, {
            "name": "ru'h",
            "class": "ró'",
            "plurality": "singular",
            "person": "third",
            "describe": "objectAccusational/locational"
        }, {
            "name": "du'h",
            "class": "dó'",
            "plurality": "singular",
            "person": "third",
            "describe": "objectAccusational/locational"
        }, {
            "name": "'hyə",
            "class": "ɛ́'/ɛ̀'",
            "plurality": "undefined",
            "person": "undefined",
            "describe": "accusational"
        }, {
            "name": "'hkə",
            "class": "ù'/ɔ́'/kə́'/k̀ʌ'/ḱ'",
            "plurality": "undefined",
            "person": "undefined",
            "describe": "objectivalPronounPosessives/objectivalPronounSingular/objectivalPronounFirstPerson/objectivalPronounSecondPerson/objectivalPronounPlural"
        }, {
            "name": "'ha",
            "class": "ɔ́'/áŋ'/à'/cə́'/c̀ʌ'/ə́ŋ'/ə̀'",
            "plurality": "undefined",
            "person": "undefined",
            "describe": "objectivalPronounPosessives/objectivalPronounSingular/objectivalPronounFirstPerson/objectivalPronounSecondPerson/objectivalPronounPlural/objectivalPronounThirdPerson"
        }, {
            "name": "'hə",
            "class": "ə́ŋ'/ə̀'",
            "plurality": "undefined",
            "person": "undefined",
            "describe": "objectivalPronounPosessives/objectivalPronounSingular/objectivalPronounFirstPerson/objectivalPronounSecondPerson/objectivalPronounPlural"
        }, {
            "name": "'hɛ",
            "class": "ɛ́'/ɛ̀'",
            "plurality": "undefined",
            "person": "undefined",
            "describe": "objectivalPronounPosessives/objectivalPronounSingular/objectivalPronounFirstPerson/objectivalPronounSecondPerson/objectivalPronounPlural"
        }, {
            "name": "'hrə",
            "class": "rə́'/r̀ʌ'/ró'/nɔ́'",
            "plurality": "undefined",
            "person": "undefined",
            "describe": "objectivalPronounPosessives/objectivalPronounSingular/objectivalPronounFirstPerson/objectivalPronounSecondPerson/objectivalPronounPlural"
        }, {
            "name": "'hnə",
            "class": "nə́'/ǹʌ'",
            "plurality": "undefined",
            "person": "undefined",
            "describe": "objectivalPronounPosessives/objectivalPronounSingular/objectivalPronounFirstPerson/objectivalPronounSecondPerson/objectivalPronounPlural"
        }, {
            "name": "'htə",
            "class": "tə́'/t̀ʌ'/t́'/t'",
            "plurality": "undefined",
            "person": "undefined",
            "describe": "objectivalPronounPosessives/objectivalPronounSingular/objectivalPronounFirstPerson/objectivalPronounSecondPerson/objectivalPronounPlural"
        }, {
            "name": "'hpə",
            "class": "pə́'/p̀ʌ'",
            "plurality": "undefined",
            "person": "undefined",
            "describe": "objectivalPronounPosessives/objectivalPronounSingular/objectivalPronounFirstPerson/objectivalPronounSecondPerson/objectivalPronounPlural"
        }, {
            "name": "'hŋə",
            "class": "cə́'/c̀ʌ'/ə́ŋ'/ə̀'",
            "plurality": "undefined",
            "person": "undefined",
            "describe": "objectivalPronounPosessives/objectivalPronounSingular/objectivalPronounFirstPerson/objectivalPronounSecondPerson/objectivalPronounPlural"
        }, {
            "name": "'hdə",
            "class": "də́'/d̀ʌ'/dó'/d̀ʌ'",
            "plurality": "undefined",
            "person": "undefined",
            "describe": "objectivalPronounPosessives/objectivalPronounSingular/objectivalPronounFirstPerson/objectivalPronounSecondPerson/objectivalPronounPlural"
        }, {
            "name": "'hmə",
            "class": "mə́'/m̀ʌ'",
            "plurality": "undefined",
            "person": "undefined",
            "describe": "objectivalPronounPosessives/objectivalPronounSingular/objectivalPronounFirstPerson/objectivalPronounSecondPerson/objectivalPronounPlural"
        }, {
            "name": "'hɔkə",
            "class": "ù'/ɔ́'",
            "plurality": "undefined",
            "person": "undefined",
            "describe": "objectivalPronounPosessives/objectivalPronounSingular/objectivalPronounFirstPerson/objectivalPronounSecondPerson/objectivalPronounPlural"
        }, {
            "name": "'haŋə",
            "class": "ɔ́'/áŋ'/à'/cə́'/c̀ʌ'/ə́ŋ'/ə̀'",
            "plurality": "undefined",
            "person": "undefined",
            "describe": "objectivalPronounPosessives/objectivalPronounSingular/objectivalPronounFirstPerson/objectivalPronounSecondPerson/objectivalPronounPlural/objectivalPronounThirdPerson"
        }, {
            "name": "'həŋə",
            "class": "ə́ŋ'/ə̀'",
            "plurality": "undefined",
            "person": "undefined",
            "describe": "objectivalPronounPosessives/objectivalPronounSingular/objectivalPronounFirstPerson/objectivalPronounSecondPerson/objectivalPronounPlural"
        }, {
            "name": "'hɛyɛ",
            "class": "ɛ́'/ɛ̀'",
            "plurality": "undefined",
            "person": "undefined",
            "describe": "objectivalPronounPosessives/objectivalPronounSingular/objectivalPronounFirstPerson/objectivalPronounSecondPerson/objectivalPronounPlural"
        }, {
            "name": "'hərə",
            "class": "rə́'/r̀ʌ'/ró'",
            "plurality": "undefined",
            "person": "undefined",
            "describe": "objectivalPronounPosessives/objectivalPronounSingular/objectivalPronounFirstPerson/objectivalPronounSecondPerson/objectivalPronounPlural"
        }, {
            "name": "'hənə",
            "class": "nə́'/ǹʌ'",
            "plurality": "undefined",
            "person": "undefined",
            "describe": "objectivalPronounPosessives/objectivalPronounSingular/objectivalPronounFirstPerson/objectivalPronounSecondPerson/objectivalPronounPlural"
        }, {
            "name": "'həkə",
            "class": "kə́'/k̀ʌ'/ḱ'/ɔ́'",
            "plurality": "undefined",
            "person": "undefined",
            "describe": "objectivalPronounPosessives/objectivalPronounSingular/objectivalPronounFirstPerson/objectivalPronounSecondPerson/objectivalPronounPlural"
        }, {
            "name": "'hətə",
            "class": "tə́'/t̀ʌ'/t́'/t'",
            "plurality": "undefined",
            "person": "undefined",
            "describe": "objectivalPronounPosessives/objectivalPronounSingular/objectivalPronounFirstPerson/objectivalPronounSecondPerson/objectivalPronounPlural"
        }, {
            "name": "'həpə",
            "class": "pə́'/p̀ʌ'",
            "plurality": "undefined",
            "person": "undefined",
            "describe": "objectivalPronounPosessives/objectivalPronounSingular/objectivalPronounFirstPerson/objectivalPronounSecondPerson/objectivalPronounPlural"
        }, {
            "name": "'həŋə",
            "class": "cə́'/c̀ʌ'/ə́ŋ'/ə̀'",
            "plurality": "undefined",
            "person": "undefined",
            "describe": "objectivalPronounPosessives/objectivalPronounSingular/objectivalPronounFirstPerson/objectivalPronounSecondPerson/objectivalPronounPlural"
        }, {
            "name": "'hədə",
            "class": "də́'/d̀ʌ'",
            "plurality": "undefined",
            "person": "undefined",
            "describe": "objectivalPronounPosessives/objectivalPronounSingular/objectivalPronounFirstPerson/objectivalPronounSecondPerson/objectivalPronounPlural"
        }, {
            "name": "'həmə",
            "class": "mə́'/m̀ʌ'",
            "plurality": "undefined",
            "person": "undefined",
            "describe": "objectivalPronounPosessives/objectivalPronounSingular/objectivalPronounFirstPerson/objectivalPronounSecondPerson/objectivalPronounPlural"
        }, {
            "name": "'hkʌ",
            "class": "ù'/ɔ́'/kə́'/k̀ʌ'/ḱ'",
            "plurality": "undefined",
            "person": "undefined",
            "describe": "objectivalPronounPosessives/objectivalPronounPlural/objectivalPronounThirdPerson"
        }, {
            "name": "'hɪ",
            "class": "ə́ŋ'/ə̀'",
            "plurality": "undefined",
            "person": "undefined",
            "describe": "objectivalPronounPosessives/objectivalPronounPlural/objectivalPronounThirdPerson"
        }, {
            "name": "'hi",
            "class": "ɛ́'/ɛ̀'",
            "plurality": "undefined",
            "person": "undefined",
            "describe": "objectivalPronounPosessives/objectivalPronounPlural/objectivalPronounThirdPerson"
        }, {
            "name": "'hrʌ",
            "class": "rə́'/r̀ʌ'/ró'",
            "plurality": "undefined",
            "person": "undefined",
            "describe": "objectivalPronounPosessives/objectivalPronounPlural/objectivalPronounThirdPerson"
        }, {
            "name": "'hnʌ",
            "class": "nə́'/ǹʌ'",
            "plurality": "undefined",
            "person": "undefined",
            "describe": "objectivalPronounPosessives/objectivalPronounPlural/objectivalPronounThirdPerson"
        }, {
            "name": "'htʌ",
            "class": "tə́'/t̀ʌ'/t́'/t'",
            "plurality": "undefined",
            "person": "undefined",
            "describe": "objectivalPronounPosessives/objectivalPronounPlural/objectivalPronounThirdPerson"
        }, {
            "name": "'hpʌ",
            "class": "pə́'/p̀ʌ'",
            "plurality": "undefined",
            "person": "undefined",
            "describe": "objectivalPronounPosessives/objectivalPronounPlural/objectivalPronounThirdPerson"
        }, {
            "name": "'hkʌ",
            "class": "cə́'/c̀ʌ'/ə́ŋ'/ə̀'",
            "plurality": "undefined",
            "person": "undefined",
            "describe": "objectivalPronounPosessives/objectivalPronounPlural/objectivalPronounThirdPerson"
        }, {
            "name": "'hdʌ",
            "class": "də́'/d̀ʌ'",
            "plurality": "undefined",
            "person": "undefined",
            "describe": "objectivalPronounPosessives/objectivalPronounPlural/objectivalPronounThirdPerson"
        }, {
            "name": "'hmʌ",
            "class": "mə́'/m̀ʌ'",
            "plurality": "undefined",
            "person": "undefined",
            "describe": "objectivalPronounPosessives/objectivalPronounPlural/objectivalPronounThirdPerson"
        }, {
            "name": "'hka",
            "class": "ù'/ɔ́'/kə́'/k̀ʌ'/ḱ'",
            "plurality": "undefined",
            "person": "undefined",
            "describe": "infinitivalPosessives"
        }, {
            "name": "'hŋa",
            "class": "ɔ́'/áŋ'/à'/cə́'/c̀ʌ'/ə́ŋ'/ə̀'/ə́ŋ'/ə̀'",
            "plurality": "undefined",
            "person": "undefined",
            "describe": "infinitivalPosessives"
        }, {
            "name": "'hya",
            "class": "ɛ́'/ɛ̀'",
            "plurality": "undefined",
            "person": "undefined",
            "describe": "infinitivalPosessives"
        }, {
            "name": "'hra",
            "class": "rə́'/r̀ʌ'/ró'",
            "plurality": "undefined",
            "person": "undefined",
            "describe": "infinitivalPosessives"
        }, {
            "name": "'hna",
            "class": "nə́'/ǹʌ'",
            "plurality": "undefined",
            "person": "undefined",
            "describe": "infinitivalPosessives"
        }, {
            "name": "'hta",
            "class": "tə́'/t̀ʌ'/t́'/t'",
            "plurality": "undefined",
            "person": "undefined",
            "describe": "infinitivalPosessives"
        }, {
            "name": "'hpa",
            "class": "pə́'/p̀ʌ'",
            "plurality": "undefined",
            "person": "undefined",
            "describe": "infinitivalPosessives"
        }, {
            "name": "'hŋa",
            "class": "cə́'/c̀ʌ'/ə́ŋ'/ə̀'",
            "plurality": "undefined",
            "person": "undefined",
            "describe": "infinitivalPosessives"
        }, {
            "name": "'hda",
            "class": "də́'/d̀ʌ'/dó'/d̀ʌ'",
            "plurality": "undefined",
            "person": "undefined",
            "describe": "infinitivalPosessives"
        }, {
            "name": "'hma",
            "class": "mə́'/m̀ʌ'",
            "plurality": "undefined",
            "person": "undefined",
            "describe": "infinitivalPosessives"
        }, {
            "name": "'hyɛrʌŋ",
            "class": "ɔ́'/áŋ'/à'/cə́'/c̀ʌ'/ə́ŋ'/ə̀'/ɛ́'/ɛ̀'/aŋ'/a'/ɛ'",
            "plurality": "undefined",
            "person": "undefined",
            "describe": "numerical"
        }, {
            "name": "'hŋarʌŋ",
            "class": "áŋ'/à'/cə́'/c̀ʌ'/aŋ'/a'",
            "plurality": "undefined",
            "person": "undefined",
            "describe": "numerical"
        }, {
            "name": "'hyaɪlɛ",
            "class": "ɔ́'/áŋ'/à'/cə́'/c̀ʌ'/ə́ŋ'/ə̀'/ɛ́'/ɛ̀'/aŋ'/a'/ɛ'",
            "plurality": "undefined",
            "person": "undefined",
            "describe": "numerical"
        }, {
            "name": "'htamaθukin",
            "class": "ɔ́'/áŋ'/à'/cə́'/c̀ʌ'/ə́ŋ'/ə̀'/aŋ'/a'",
            "plurality": "undefined",
            "person": "undefined",
            "describe": "numerical"
        }, {
            "name": "'htamaθuyɛrʌŋ",
            "class": "ɔ́'/áŋ'/à'/cə́'/c̀ʌ'/ə́ŋ'/ə̀'/aŋ'/a'",
            "plurality": "undefined",
            "person": "undefined",
            "describe": "numerical"
        }, {
            "name": "'htamaθusas",
            "class": "ɔ́'/áŋ'/à'/cə́'/c̀ʌ'/ə́ŋ'/ə̀'/aŋ'/a'",
            "plurality": "undefined",
            "person": "undefined",
            "describe": "numerical"
        }, {
            "name": "'htamaθuyaɪlɛ",
            "class": "ɔ́'/áŋ'/à'/cə́'/c̀ʌ'/ə́ŋ'/ə̀'/aŋ'/a'",
            "plurality": "undefined",
            "person": "undefined",
            "describe": "numerical"
        }, {
            "name": "'hŋin",
            "class": "ə́ŋ'/ə̀'/əŋ'/ə'",
            "plurality": "undefined",
            "person": "undefined",
            "describe": "numerical"
        }, {
            "name": "'hrim",
            "class": "rə́'/r̀ʌ'/rə'/rʌ'",
            "plurality": "undefined",
            "person": "undefined",
            "describe": "numerical"
        }, {
            "name": "'hdim",
            "class": "rə́'/r̀ʌ'/rə'/rʌ'",
            "plurality": "undefined",
            "person": "undefined",
            "describe": "numerical"
        }, {
            "name": "'hnin",
            "class": "nə́'/ǹʌ'/nə'/nʌ'",
            "plurality": "undefined",
            "person": "undefined",
            "describe": "numerical"
        }, {
            "name": "'hnɛrʌŋ",
            "class": "nə́'/ǹʌ'/nə'/nʌ'",
            "plurality": "undefined",
            "person": "undefined",
            "describe": "numerical"
        }, {
            "name": "'hkin",
            "class": "kə́'/k̀ʌ'/ḱ'/kə'/kʌ'",
            "plurality": "undefined",
            "person": "undefined",
            "describe": "numerical"
        }, {
            "name": "'htin",
            "class": "tə́'/t̀ʌ'/t́'/t'/tə'/tʌ'/kə́'/k̀ʌ'/ḱ'/kə'/kʌ'",
            "plurality": "undefined",
            "person": "undefined",
            "describe": "numerical"
        }, {
            "name": "'htʌrʌŋ",
            "class": "tə́'/t̀ʌ'/t́'/t'/tə'/tʌ'/kə́'/k̀ʌ'/ḱ'/kə'/kʌ'",
            "plurality": "undefined",
            "person": "undefined",
            "describe": "numerical"
        }, {
            "name": "'htaɪlɛ",
            "class": "tə́'/t̀ʌ'/t́'/t'/tə'/tʌ'/kə́'/k̀ʌ'/ḱ'/kə'/kʌ'",
            "plurality": "undefined",
            "person": "undefined",
            "describe": "numerical"
        }, {
            "name": "'hwin",
            "class": "pə́'/p̀ʌ'/pə'/pʌ'",
            "plurality": "undefined",
            "person": "undefined",
            "describe": "numerical"
        }, {
            "name": "'hpiŋ",
            "class": "pə́'/p̀ʌ'/pə'/pʌ'",
            "plurality": "undefined",
            "person": "undefined",
            "describe": "numerical"
        }, {
            "name": "'hpʌrʌŋ",
            "class": "pə́'/p̀ʌ'/pə'/pʌ'",
            "plurality": "undefined",
            "person": "undefined",
            "describe": "numerical"
        }, {
            "name": "'hpaɪlɛ",
            "class": "pə́'/p̀ʌ'/pə'/pʌ'",
            "plurality": "undefined",
            "person": "undefined",
            "describe": "numerical"
        }, {
            "name": "'hŋin",
            "class": "cə́'/c̀ʌ'/ə́ŋ'/ə̀'/cə'/cʌ'",
            "plurality": "undefined",
            "person": "undefined",
            "describe": "numerical"
        }, {
            "name": "'hpʌrʌŋ",
            "class": "cə́'/c̀ʌ'/ə́ŋ'/ə̀'/cə'/cʌ'",
            "plurality": "undefined",
            "person": "undefined",
            "describe": "numerical"
        }, {
            "name": "'hpaɪlɛ",
            "class": "cə́'/c̀ʌ'/ə́ŋ'/ə̀'/cə'/cʌ'",
            "plurality": "undefined",
            "person": "undefined",
            "describe": "numerical"
        }, {
            "name": "'hdim",
            "class": "də́'/d̀ʌ'/də'/dʌ'",
            "plurality": "undefined",
            "person": "undefined",
            "describe": "numerical"
        }, {
            "name": "'hmin",
            "class": "mə́'/m̀ʌ'/mə'/mʌ'",
            "plurality": "undefined",
            "person": "undefined",
            "describe": "numerical"
        }, {
            "name": "'hmərʌŋ",
            "class": "mə́'/m̀ʌ'/mə'/mʌ'",
            "plurality": "undefined",
            "person": "undefined",
            "describe": "numerical"
        }, {
            "name": "'hmaɪlɛ",
            "class": "mə́'/m̀ʌ'/mə'/mʌ'",
            "plurality": "undefined",
            "person": "undefined",
            "describe": "numerical"
        }, {
            "name": "miŋ'h",
            "class": "undefined",
            "plurality": "undefined",
            "person": "undefined",
            "describe": "undefined"
        }, {
            "name": "muŋ'h",
            "class": "undefined",
            "plurality": "undefined",
            "person": "undefined",
            "describe": "undefined"
        }, {
            "name": "sā'h",
            "class": "undefined",
            "plurality": "undefined",
            "person": "undefined",
            "describe": "undefined"
        }, {
            "name": "kɔŋ'h",
            "class": "undefined",
            "plurality": "undefined",
            "person": "undefined",
            "describe": "undefined"
        }, {
            "name": "nāŋ'h",
            "class": "undefined",
            "plurality": "undefined",
            "person": "undefined",
            "describe": "undefined"
        }, {
            "name": "ŋā'h",
            "class": "undefined",
            "plurality": "undefined",
            "person": "undefined",
            "describe": "undefined"
        }, {
            "name": "kə'h",
            "class": "undefined",
            "plurality": "undefined",
            "person": "undefined",
            "describe": "undefined"
        }, {
            "name": "rə'h",
            "class": "undefined",
            "plurality": "undefined",
            "person": "undefined",
            "describe": "undefined"
        }, {
            "name": "də'h",
            "class": "undefined",
            "plurality": "undefined",
            "person": "undefined",
            "describe": "undefined"
        }, {
            "name": "əŋ'h",
            "class": "undefined",
            "plurality": "undefined",
            "person": "undefined",
            "describe": "undefined"
        }, {
            "name": "ɔ'h",
            "class": "undefined",
            "plurality": "undefined",
            "person": "undefined",
            "describe": "undefined"
        }, {
            "name": "tə'h",
            "class": "undefined",
            "plurality": "undefined",
            "person": "undefined",
            "describe": "undefined"
        }, {
            "name": "pə'h",
            "class": "undefined",
            "plurality": "undefined",
            "person": "undefined",
            "describe": "undefined"
        }, {
            "name": "mə'h",
            "class": "undefined",
            "plurality": "undefined",
            "person": "undefined",
            "describe": "undefined"
        }, {
            "name": "ɛ'h",
            "class": "undefined",
            "plurality": "undefined",
            "person": "undefined",
            "describe": "undefined"
        }, {
            "name": "mə'h",
            "class": "undefined",
            "plurality": "undefined",
            "person": "undefined",
            "describe": "undefined"
        }, {
            "name": "aŋ'h",
            "class": "undefined",
            "plurality": "undefined",
            "person": "undefined",
            "describe": "undefined"
        }, {
            "name": "kʌ'h",
            "class": "undefined",
            "plurality": "undefined",
            "person": "undefined",
            "describe": "undefined"
        }, {
            "name": "rʌ'h",
            "class": "undefined",
            "plurality": "undefined",
            "person": "undefined",
            "describe": "undefined"
        }, {
            "name": "dʌ'h",
            "class": "undefined",
            "plurality": "undefined",
            "person": "undefined",
            "describe": "undefined"
        }, {
            "name": "ə'h",
            "class": "undefined",
            "plurality": "undefined",
            "person": "undefined",
            "describe": "undefined"
        }, {
            "name": "u'h",
            "class": "undefined",
            "plurality": "undefined",
            "person": "undefined",
            "describe": "undefined"
        }, {
            "name": "tʌ'h",
            "class": "undefined",
            "plurality": "undefined",
            "person": "undefined",
            "describe": "undefined"
        }, {
            "name": "pʌ'h",
            "class": "undefined",
            "plurality": "undefined",
            "person": "undefined",
            "describe": "undefined"
        }, {
            "name": "mʌ'h",
            "class": "undefined",
            "plurality": "undefined",
            "person": "undefined",
            "describe": "undefined"
        }, {
            "name": "ɛ'h",
            "class": "undefined",
            "plurality": "undefined",
            "person": "undefined",
            "describe": "undefined"
        }, {
            "name": "mʌ'h",
            "class": "undefined",
            "plurality": "undefined",
            "person": "undefined",
            "describe": "undefined"
        }, {
            "name": "a'h",
            "class": "undefined",
            "plurality": "undefined",
            "person": "undefined",
            "describe": "undefined"
        }
    ]

    function get(tex) {

        for (var i = 0; i < pronouns.length; i++) {

            if (pronouns[i].name == tex) {

                return pronouns[i];
            }

        }

        return "n/a";

    }

    function subjectPronouns() {

        var subjectProunouns = HelperFunctions
            .createSubsectionArrayForObjects(pronouns,
                "describe", "subject");

        return subjectProunouns;
    }
	
	function allPronum(){
		
		return HelperFunctions.flattenArrayByAttribute(pronouns, 'name');
	}
	
	 function getPronouns (closedClass) {

        var temp = HelperFunctions.
            findCommonAndDifferentElements(closedClass, lookForPronouns.allPronum());

        return {
            pronum: temp.common,
            left: temp.different
        }
    }

    return {

        get: get,
        subjectPronouns: subjectPronouns,
		allPronum : allPronum,
		getPronouns : getPronouns
    }

})();
